# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ['*'] # votre frontend
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/': # Applique le CORS aux routes commençant par /api/
            allow_origin: ['http://localhost:5173/']